sudo: required
language: node_js
notifications:
  email: thiago.p.magalhaes@gmail.com
node_js:
- 8.10.0
services:
- postgresql
env:
  global:
    - NODE_ENV: test
    - TRAVIS: true
    - PGPORT: 5433
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
before_script:
- psql -c 'create database ts_api_test;' -U postgres
- npm i -g sequelize-cli gulp-cli
- cd server/
- sequelize db:migrate --env test
- npm install
- gulp
script:
- npm run unit-test
- npm run integration-test