sudo: required
language: node_js
notifications:
  email: thiago.p.magalhaes@gmail.com
node_js:
- 8.10.0
services:
- postgresql
env:
  global:
    - NODE_ENV: test
    - TRAVIS: true
addons:
  postgresql: '9.6'
before_script:
- psql -c 'create database ts_api_test;' -U postgres
- npm install mysql -g
- npm i -g sequelize-cli gulp-cli sequelize
- cd server/
- sequelize init
- sequelize db:migrate --env test
- npm install
- gulp
script:
- npm run unit-test
- npm run integration-test